"""Post Selector - Laminated Timber Post Capacity Calculator"""

from .core import (
    CityNotFoundError,
    AmbiguousCityError,
    ClimaticLoads,
    BuildingParams,
    PostProperties,
    SnowLoadResult,
    WindLoadResult,
    LoadingResult,
    CapacityResult,
    FullResult,
    load_cities_from_csv,
    find_city,
    get_city_db,
    get_post,
    calculate_snow_load,
    calculate_wind_load,
    calculate_loading,
    calculate_capacity,
    run_calculation,
    run_validation,
    POST_DATABASE,
    PSF_TO_KPA,
    FT_TO_M,
    IN_TO_MM,
    GIRT_SPACING_IN,
    DEFAULT_EMBED_DEPTH_FT,
    K_SPLICE,
)

__version__ = "1.0.0"
__all__ = [
    "CityNotFoundError",
    "AmbiguousCityError",
    "ClimaticLoads",
    "BuildingParams",
    "PostProperties",
    "SnowLoadResult",
    "WindLoadResult",
    "LoadingResult",
    "CapacityResult",
    "FullResult",
    "load_cities_from_csv",
    "find_city",
    "get_city_db",
    "get_post",
    "calculate_snow_load",
    "calculate_wind_load",
    "calculate_loading",
    "calculate_capacity",
    "run_calculation",
    "run_validation",
    "POST_DATABASE",
    "PSF_TO_KPA",
    "FT_TO_M",
    "IN_TO_MM",
    "GIRT_SPACING_IN",
    "DEFAULT_EMBED_DEPTH_FT",
    "K_SPLICE",
]
